# Generated by Django 5.1.7 on 2025-03-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment_author_news_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('can_delete_comment', 'Может удалять комментарии')]},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': [('can_edit_news', 'Может редактировать новости'), ('can_delete_news', 'Может удалять новости')]},
        ),
    ]
